export class OrderInfo {
    OrderType: string = "";
    BillingTypeNumber: string = "";
    BillingTypeName: string = "";
    DeliveryType: string = "";
    PONumber: string = "";
    AlternateShippingAddress: string = "";
    SpecialInstructions: string = "";
    UserId: string = "";
    BranchCode: string = "";
    CustomerNumber: string = "";
    CustomerName1: string = "";
    CustomerName2: string = "";
    Address: string = "";
    City: string = "";
    State: string = "";
    Zip: string = "";
    Phone: string = "";
    SalesPerson: string = "";
    MSC: string = "";
    Total: number = 0;
    IsAlternateAddressEdited: boolean = false;
    includePurchaseOrder: boolean = true;
    UnitNumber: string = "";

    //Id: string;
    //ErrorCode: string;
    //ErrorMessage: string;
    //Message: string;
    //SapOrderNumber: string;
    //SapErrorMessage: string;
    //Type: string;
    //BranchCode: string;
    //Total: number;
    //DateCreated: Date;
    //CreatedBy: string;
    //CustomerId: string;
    //ShipToAddressNo: string;
    //BillToAddressNo: string;
    //ShippingInstructions: string;
    //ShipMethod: string;
    //PONumber: string;
    //Name1: string;
    //Address: string;
    //City: string;
    //State: string;
    //Zip: string;
    //Phone: string;
    //CartId: string;
    //OrderItemId: string;
    //OrderId: string;
    //PartNumber: string;
    //Description: string;
    //CustomerPrice: number;
    //ListPrice: number;
    //FinalPrice: number;
    //ExtendedPrice: number;
    //AdjustedPrice: number;
    //Quantity: number;
    //PartId: string;
    //QuantityConfirm: number;
    //BillingType: string;
    //DeliveryOptions: string;
    //SpecialInstructions: string;
    //Name2: string;
    //SalesPerson: string;
    //MSC: string;
    //PartNumOnly: string;
    //IsBuyOut: boolean;
    //IsRTCDelivery: boolean;
    //IsCustomerDelivery: boolean;
    //IsFreight: boolean;
}