"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var OrderInfo = (function () {
    function OrderInfo() {
        this.OrderType = "";
        this.BillingTypeNumber = "";
        this.BillingTypeName = "";
        this.DeliveryType = "";
        this.PONumber = "";
        this.AlternateShippingAddress = "";
        this.SpecialInstructions = "";
        this.UserId = "";
        this.BranchCode = "";
        this.CustomerNumber = "";
        this.CustomerName1 = "";
        this.CustomerName2 = "";
        this.Address = "";
        this.City = "";
        this.State = "";
        this.Zip = "";
        this.Phone = "";
        this.SalesPerson = "";
        this.MSC = "";
        this.Total = 0;
        this.IsAlternateAddressEdited = false;
        this.includePurchaseOrder = true;
        this.UnitNumber = "";
        //Id: string;
        //ErrorCode: string;
        //ErrorMessage: string;
        //Message: string;
        //SapOrderNumber: string;
        //SapErrorMessage: string;
        //Type: string;
        //BranchCode: string;
        //Total: number;
        //DateCreated: Date;
        //CreatedBy: string;
        //CustomerId: string;
        //ShipToAddressNo: string;
        //BillToAddressNo: string;
        //ShippingInstructions: string;
        //ShipMethod: string;
        //PONumber: string;
        //Name1: string;
        //Address: string;
        //City: string;
        //State: string;
        //Zip: string;
        //Phone: string;
        //CartId: string;
        //OrderItemId: string;
        //OrderId: string;
        //PartNumber: string;
        //Description: string;
        //CustomerPrice: number;
        //ListPrice: number;
        //FinalPrice: number;
        //ExtendedPrice: number;
        //AdjustedPrice: number;
        //Quantity: number;
        //PartId: string;
        //QuantityConfirm: number;
        //BillingType: string;
        //DeliveryOptions: string;
        //SpecialInstructions: string;
        //Name2: string;
        //SalesPerson: string;
        //MSC: string;
        //PartNumOnly: string;
        //IsBuyOut: boolean;
        //IsRTCDelivery: boolean;
        //IsCustomerDelivery: boolean;
        //IsFreight: boolean;
    }
    return OrderInfo;
}());
exports.OrderInfo = OrderInfo;
//# sourceMappingURL=order-info.entity.js.map